name: custom env var 


on: workflow_dispatch

env: 
  DAY_OF_WEEK: friday
  testvar: value1

jobs:
  build:
    name: print the env var
    runs-on: ubuntu-latest

    env: 
      greeting: dear
      testvar: value2

    steps:
    - name: print the values of env var
      run: |
        echo "the value of DAY_OF_WEEK is $DAY_OF_WEEK"
        echo "the value of greeting is $greeting"
        echo "the value of testvar is $testvar"

      env: 
        DAY_OF_WEEK: monday
        testvar: value3





